### ISSUE TITLE
Panel not found

### ISSUE THREAD

**Issue by ahhfat** [mahendrapaipuri/grafana-dashboard-reporter-app#219]
Grafana version : Grafana v11.4.0

![image](https://github.com/user-attachments/assets/60cbdf05-35f5-4c0c-8dcd-a1b58201093f)

Token manually generated 
![image](https://github.com/user-attachments/assets/1c9dc3d6-956b-4ce2-b908-77557faa203d)

Log :
```
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-12-30T03:41:48.761033189Z level=info msg="generate report using config: Theme: light; Orientation: portrait; Layout: simple; Dashboard Mode: full; Time Zone: ; Encoded Logo: ; Max Renderer Workers: 4; Max Browser Workers: 2; Remote Chrome Addr: ; App URL: http://localhost:3000/; TLS Skip verifiy: true; Included Panel IDs: all; Excluded Panel IDs: none Included Data for Panel IDs: none" endpoint=callResource pluginID=mahendrapaipuri-dashboardreporter-app
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-12-30T03:41:48.76179721Z level=info msg="generate report using local chrome" endpoint=callResource pluginID=mahendrapaipuri-dashboardreporter-app
logger=context userId=0 orgId=0 uname= t=2024-12-30T03:41:49.460429884Z level=info msg= error="[auth.unauthorized] cannot authenticate request" remote_addr=127.0.0.1 traceID=
logger=context userId=0 orgId=0 uname= t=2024-12-30T03:41:49.461734472Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=127.0.0.1 time_ms=1 duration=1.706359ms size=102 referer= handler=/api/live/ws status_source=server
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-12-30T03:41:49.520925158Z level=error msg="could not unmarshal event: %v" EXTRA_VALUE_AT_END="unknown ClientNavigationReason value: initialFrameNavigation" endpoint=callResource pluginID=mahendrapaipuri-dashboardreporter-app subsystem=chromium
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-12-30T03:41:49.524419289Z level=error msg="could not unmarshal event: %v" pluginID=mahendrapaipuri-dashboardreporter-app subsystem=chromium EXTRA_VALUE_AT_END="unknown ClientNavigationReason value: initialFrameNavigation" endpoint=callResource
logger=context userId=0 orgId=0 uname= t=2024-12-30T03:41:50.432372468Z level=info msg= error="[auth.unauthorized] cannot authenticate request" remote_addr=127.0.0.1 traceID=
logger=context userId=0 orgId=0 uname= t=2024-12-30T03:41:50.432582526Z level=info msg="Request Completed" method=GET path=/api/live/ws status=401 remote_addr=127.0.0.1 time_ms=0 duration=309.965µs size=102 referer= handler=/api/live/ws status_source=server
logger=rendering renderer=plugin t=2024-12-30T03:41:51.059007925Z level=info msg=Rendering path="d-solo/c3738322-cba8-40a7-8a03-a11872ee70db/_?from=now-6h&height=500&panelId=0&theme=light&to=now&width=1000" userID=22
logger=rendering renderer=plugin t=2024-12-30T03:41:51.07015329Z level=info msg=Rendering path="d-solo/c3738322-cba8-40a7-8a03-a11872ee70db/_?from=now-6h&height=500&panelId=0&theme=light&to=now&width=1000" userID=22
logger=rendering renderer=plugin t=2024-12-30T03:41:51.094639903Z level=info msg=Rendering path="d-solo/c3738322-cba8-40a7-8a03-a11872ee70db/_?from=now-6h&height=500&panelId=0&theme=light&to=now&width=1000" userID=22
logger=rendering renderer=plugin t=2024-12-30T03:41:51.128662863Z level=info msg=Rendering path="d-solo/c3738322-cba8-40a7-8a03-a11872ee70db/_?from=now-6h&height=500&panelId=0&theme=light&to=now&width=1000" userID=22
logger=context userId=22 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-12-30T03:41:52.453513604Z level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=127.0.0.1 time_ms=1 duration=1.627726ms size=0 referer= handler=/api/live/ws status_source=server
logger=context userId=22 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-12-30T03:41:52.495737265Z level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=127.0.0.1 time_ms=5 duration=5.091897ms size=0 referer= handler=/api/live/ws status_source=server
logger=context userId=22 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-12-30T03:41:52.588346947Z level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=127.0.0.1 time_ms=1 duration=1.842518ms size=0 referer= handler=/api/live/ws status_source=server
logger=context userId=22 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-12-30T03:41:52.617080151Z level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=127.0.0.1 time_ms=1 duration=1.920222ms size=0 referer= handler=/api/live/ws status_source=server
logger=rendering renderer=plugin t=2024-12-30T03:41:53.899293998Z level=info msg=Rendering path="d-solo/c3738322-cba8-40a7-8a03-a11872ee70db/_?from=now-6h&height=500&panelId=0&theme=light&to=now&width=1000" userID=22
logger=rendering renderer=plugin t=2024-12-30T03:41:53.905884013Z level=info msg=Rendering path="d-solo/c3738322-cba8-40a7-8a03-a11872ee70db/_?from=now-6h&height=500&panelId=0&theme=light&to=now&width=1000" userID=22
logger=rendering renderer=plugin t=2024-12-30T03:41:54.032079988Z level=info msg=Rendering path="d-solo/c3738322-cba8-40a7-8a03-a11872ee70db/_?from=now-6h&height=500&panelId=0&theme=light&to=now&width=1000" userID=22
logger=rendering renderer=plugin t=2024-12-30T03:41:54.045134888Z level=info msg=Rendering path="d-solo/c3738322-cba8-40a7-8a03-a11872ee70db/_?from=now-6h&height=500&panelId=0&theme=light&to=now&width=1000" userID=22
logger=context userId=22 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-12-30T03:41:55.348562749Z level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=127.0.0.1 time_ms=4 duration=4.527964ms size=0 referer= handler=/api/live/ws status_source=server
logger=context userId=22 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-12-30T03:41:55.40146607Z level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=127.0.0.1 time_ms=2 duration=2.683861ms size=0 referer= handler=/api/live/ws status_source=server
logger=context userId=22 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-12-30T03:41:55.460324599Z level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=127.0.0.1 time_ms=1 duration=1.675167ms size=0 referer= handler=/api/live/ws status_source=server
logger=context userId=22 orgId=1 uname=sa-1-extsvc-mahendrapaipuri-dashboardreporter-app t=2024-12-30T03:41:55.469859916Z level=info msg="Request Completed" method=GET path=/api/live/ws status=-1 remote_addr=127.0.0.1 time_ms=5 duration=5.785484ms size=0 referer= handler=/api/live/ws status_source=server
logger=rendering renderer=plugin t=2024-12-30T03:41:56.810838932Z level=info msg=Rendering path="d-solo/c3738322-cba8-40a7-8a03-a11872ee70db/_?from=now-6h&height=500&panelId=0&theme=light&to=now&width=1000" userID=22
logger=rendering renderer=plugin t=2024-12-30T03:41:56.824905449Z level=info msg=Rendering path="d-solo/c3738322-cba8-40a7-8a03-a11872ee70db/_?from=now-6h&height=500&panelId=0&theme=light&to=now&width=1000" userID=22
logger=rendering renderer=plugin t=2024-12-30T03:41:56.994920252Z level=info msg=Rendering path="d-solo/c3738322-cba8-40a7-8a03-a11872ee70db/_?from=now-6h&height=500&panelId=0&theme=light&to=now&width=1000" userID=22

```

**Comment by mahendrapaipuri** [comment]
Hello,

Which version of plugin are you using? Which distro are you on? How did you install chromium?

Could you please enable debug logging on Grafana server and share more logs?

Cheers

**Comment by ahhfat** [comment]
Hi Mahendra,

Plugin version : v1.7.1
Grafana Image Renderer : 3.11.6
OS : Ubuntu 24.04.1 LTS
Chromnium : apt-get install chromium-browser
Logs : 
[log-render.txt](https://github.com/user-attachments/files/18272917/log-render.txt)

**Comment by mahendrapaipuri** [comment]
Cheers for the details @ahhfat 

So, as I understand even when doing `apt-get install chromium-browser`, chromium from `snap` is getting installed. Actually I could not make the snap chromium work. I got the following errors when creating user profile directories:

```
logger=plugin.mahendrapaipuri-dashboardreporter-app t=2024-12-30T13:22:15.283501073+01:00 level=error msg="failed to start browser" endpoint=checkHealth err="couldn't create browser context: chrome failed to start:\ncmd_run.go:1276: WARNING: cannot create user data directory: cannot update the 'current' symlink of \"/usr/share/grafana/snap/chromium/current\": symlink 3010 /usr/share/grafana/snap/chromium/current: read-only file system\nneed to run as root or suid\n" pluginId=mahendrapaipuri-dashboardreporter-app
```

I assume you fixed those errors? Then I uninstalled the chromium from snap **completely (including binaries)** and then installed `google-chrome` from debian package installed from `https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb`. And then I set the env vars `XDG_CONFIG_HOME=/tmp/.chrome` and `XDG_CACHE_HOME=/tmp/.chrome` in Grafana process so when creating user profile directories, they will be created in the `/tmp/.chrome` folder. This approach worked and I could create reports.

Are you sure the browser started well with plugin? If you go to `<grafana_url>/a/mahendrapaipuri-dashboardreporter-app/status` you will see if plugin has started well or not. If everything on the browser side is working as expected, can you please try to generate report for this [sample dashboard](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/main/provisioning/dashboards/test-dashboard-collapsed.json) and see if it works? Is it possible to share your dashboard JSON model (redacting any sensitive info)?

Cheers

**Comment by ahhfat** [comment]
Hi Mahendra,

Here the information,

![image](https://github.com/user-attachments/assets/96368e1b-eadc-4ca7-b830-cea4914d6650)

Sample dashboard log : 

[log2.txt](https://github.com/user-attachments/files/18278962/log2.txt)

**Comment by mahendrapaipuri** [comment]
Cheers for the logs @ahhfat 

Unfortunately I am not able to reproduce the bug. Infact I am not able to make plugin work with chromium installed from `snap` (I do not have any experience with `snap` eco-system).

One thing you can try is to completely uninstall `chromium` installed from `snap` (including binaries) and install `google-chrome` from `https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb` and retry. I could make it work on a fresh ubuntu 24.04 install using `google-chrome`. If you choose to go this way, ensure the `chromium` binary from `snap` is removed from `PATH`.

**Comment by ahhfat** [comment]
Hi @mahendrapaipuri 

Here recent update regarding the issue. 

I remove chromium and uninstall grafana-image-renderer and grafana-dashboard-reporter-app from grafana. I used google-chrome that you suggested.

Installed version :

OS : Ubuntu 24.04.1 LTS 
Grafana : v11.4.0
Grafana-image-renderer : 3.11.6
grafana-dashboard-reporter-app : 1.7.1
google-chrome : Google Chrome 131.0.6778.204, used from what you recomended
google chrome path : /usr/bin/google-chrome
Grafana.ini : 
<img width="659" alt="image" src="https://github.com/user-attachments/assets/395e8e09-b549-4927-90d5-c62e3e08a64c" />
Log debug : 
[log3.txt](https://github.com/user-attachments/files/18327365/log3.txt)
Error : 
![image](https://github.com/user-attachments/assets/4490051d-60d8-4d57-9fb0-a17d2f77d8c5)

**Comment by mahendrapaipuri** [comment]
Thanks a lot @ahhfat for your patience.

The error you have is due to chrome not able to create user profile directories as `/usr/share/grafana` is read-only. Please set `XDG_CONFIG_HOME=/tmp/.chrome` and `XDG_CACHE_HOME=/tmp/.chrome` env vars for the Grafana server which should fix that problem.

**Comment by ahhfat** [comment]
The error still appeared

I execute 

```
export XDG_CACHE_HOME=/tmp/.chrome
export XDG_CONFIG_HOME=/tmp/.chrome
```
Result
```
root@grarana# env | grep XDG
XDG_CONFIG_HOME=/tmp/.chrome
XDG_CACHE_HOME=/tmp/.chrome
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
```
Or i just add on grafana.ini ?

**Comment by mahendrapaipuri** [comment]
If you have installed Grafana using `apt`, there will be a file `/etc/default/grafana-server` with all the environment variables set on Grafana server process. You need to add those two env vars to this file.

**Comment by mahendrapaipuri** [comment]
@ahhfat I made a new release [v1.7.2](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/releases/tag/v1.7.2) that should automatically take care of setting those env vars without having to do it by yourself. Please try it and let me know!

**Comment by ahhfat** [comment]
Hi @mahendrapaipuri 

Ive tested the new release version and its work as expected. 

![image](https://github.com/user-attachments/assets/4bdab08d-78ba-4ba1-83a8-05c892218e3e)

I just wanted to take a moment to express my sincere thanks for your hard work and dedication. I truly appreciate everything you do.

Keep up the great work!

**Comment by mahendrapaipuri** [comment]
Glad that it works as expected!!

Thanks a lot for your patient testing and reporting. It helped me to discover bugs which I eventually fixed in the new version.
