### ISSUE TITLE
Issue with Grid Layout Shrinking Panel Height in Printed Reports

### ISSUE THREAD

**Issue by mansoorulhaq324** [mahendrapaipuri/grafana-dashboard-reporter-app#272]
## **Describe the bug**

When using the Grafana Dashboard Reporter App with layout=grid, the printed report shrinks the height of panels significantly compared to their original size in the browser. This causes text to become very small and unreadable.

In contrast, when using layout=simple, the printed report maintains the correct panel proportions, and the text remains readable. However, in grid layout, the panel height is reduced disproportionately (e.g., an original height of 250 is reduced to 100 in the printed document).

I am attaching:

Dashboard JSON for reference.
Printed reports (Simple vs. Grid Layouts) to illustrate the issue.
Please let me know if you need any more details.

## **Steps to reproduce**

Just print the report in both grid and sample layout and you will see the issue

## **Grafana logs**

Logs not available because it is just layout issue

## **Screenshots**

Horizontally shrinker sample when used grid layout:

![Image](https://github.com/user-attachments/assets/bbf0a2e9-71de-4337-ad05-a72255365fc3)

Correct printing sample with simple layout

![Image](https://github.com/user-attachments/assets/0fa772a5-c0a5-4da0-8906-c9cc5a3df448)

## **Version Details:**

- Grafana version : Grafana OSS 11.5.0.0
- Grafana Image Renderer version : 3.12.0
- Reporter Plugin version : 1.7.1
- Chromium version :
- How Chromium is installed (`apt`, `yum`, `snap`, docker) :
- OS and Distro : Windows

**Comment by mahendrapaipuri** [comment]
Hello @mansoorulhaq324 

Thanks for opening this issue and a detailed report. Appreciate it.

The plugin does not change the dimensions in the grid layout. It just [converts Grafana units to pixels](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/blob/a9abe7e358c600a791323678641daeefe3cf790b/pkg/plugin/dashboard/renderer.go#L202-L204). When you said original height of 250, what are you referring to? Pixels on your browser? What is the panel dimensions in your JSON model?

Also, try the [latest](https://github.com/mahendrapaipuri/grafana-dashboard-reporter-app/releases/tag/v1.7.3) version of the plugin. Some of the bugs are fixed in the latest releases.

**Comment by mansoorulhaq324** [comment]
Hi @mahendrapaipuri,

Thanks for your quick response on this. I mean what it shows on the dashboard and when we prints its height reduces to less than 50% of the panel heigh. Like in the above 2 screenshots I share in original description. The first one shows when we print using grid layout but in actual dashboard it looks like second screenshot.

I am attaching here my dashboard JSON. One again thanks for your quick response.

Thanks!

[priniting issue-1739785850324.json](https://github.com/user-attachments/files/18826835/priniting.issue-1739785850324.json)

**Comment by mahendrapaipuri** [comment]
Cheers for the dashboard. I can reproduce the issue. I will look into it.

Thanks again for taking your time to report it!!

**Comment by mansoorulhaq324** [comment]
Hi @mahendrapaipuri,

I tested the build that you shared, but the height in the generated PDF report for the grid layout is still not correct.

I also tried creating a dashboard with a panel row, but it had no effect. I am sharing two sample dashboards:

One with only a single panel.
Another with a panel row occupying the full row width.
When you print the report in simple layout, it looks good. However, when printing in grid layout, the height is reduced, making it difficult to read.

Let me know if you need any further details.

[priniting issue single panel-1739945669794.json](https://github.com/user-attachments/files/18859936/priniting.issue.single.panel-1739945669794.json)

[priniting issue-1739945690457.json](https://github.com/user-attachments/files/18859939/priniting.issue-1739945690457.json)

**Comment by mansoorulhaq324** [comment]
Hi @mahendrapaipuri,

I agree with you and will look for some other approach for our dashboards. But sharing a comparison just to show you. I created the 2 pdf documents one using grid layout and the other using simple layout. Could you please check the attached screenshot. If it is not possible to fix then we can close this ticket.

![Image](https://github.com/user-attachments/assets/7dd0f61d-8fc4-44f9-b6f4-bdb5e62bc361)

Many thanks for your active communication and for looking into this.

Thanks!

**Comment by mahendrapaipuri** [comment]
Hello @mansoorulhaq324 

Thanks again for detailed report.

So, if you are happy with the output from simple layout, what is blocking you from using it for your use case?

I mean, you are comparing the resolution of your monitor with the resolution allowed by A4 paper, right?! The reporter effectively fits the width of your monitor to the A4 paper. That is why panels look smaller inside the report. Maybe we can look into making paper size configurable so that we can generate bigger PNGs for A3/A2/A1 sizes?!

**Comment by mansoorulhaq324** [comment]
Hi @mahendrapaipuri,

Actually our actual dashboards are much complex and we want to generate the pdf with the same layout as it is in the dashboard. For example if we use grafana cloud then it prints the pdf using the same layout. But, we cannot use grafana cloud. When we use simple layout then it is printing panels one by one and it does not preserve the layout as it is on the dashboard. 

Yes, I agree with you if we can add something like page size to make it configurable.

Cheer!

**Comment by mansoorulhaq324** [comment]
Hi @mahendrapaipuri,

I've tested the new build, and it's much improved! I really appreciate your support on this. Many thanks!

Cheers!

**Comment by mahendrapaipuri** [comment]
Thanks a lot for your time in testing the patch @mansoorulhaq324 

I am going to merge it and make a new release!
